#include "geometry.hpp"
#include "search.hpp"

#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <string>
#include <thread>

using namespace polyjam;

namespace {

struct Args {
  std::string command = "search";
  std::string piece = "cube";
  std::string shell = "cube";
  std::string output = "result.json";
  int count = 9;
  double seconds = 10.0;
  int threads = std::max(1u, std::thread::hardware_concurrency());
  std::uint64_t seed = 1;
  double start_scale = 0.0;
  double tolerance = 1e-5;
  double clearance = 0.0;
  bool progress_json = false;
};

void usage() {
  std::cout << R"(polyjam — pack identical convex polyhedra inside a convex polyhedral shell

Usage:
  polyjam search [options]
  polyjam shapes

Shape arguments accept a builtin name or an OBJ path. OBJ faces are ignored: Polyjam
computes the convex hull from all `v` records, recenters it, and normalizes circumradius to 1.

Options:
  --piece SHAPE       cube | tetra | octa | icosa | dodeca | path.obj
  --shell SHAPE       same choices; minimized by uniform scale about its centroid
  --count N           number of identical pieces (default 9)
  --seconds S         wall-clock search budget (default 10)
  --threads N         independent search workers
  --seed N            reproducibility seed
  --start-scale S     override initial shell scale heuristic
  --tolerance X       feasibility tolerance (default 1e-5)
  --clearance X       requested piece-piece clearance in normalized units
  --output FILE       write browser-readable result JSON
  --progress-json     emit best-so-far JSON lines on stdout (used by tools/server.py)

Examples:
  polyjam search --piece cube --shell cube --count 10 --seconds 30 --output web/results/cube10.json
  polyjam search --piece tetra --shell cube --count 12 --seconds 60 --output web/results/tetra12.json
  polyjam search --piece examples/wedge.obj --shell dodeca --count 7 --seconds 120
)";
}

Args parse(int argc, char** argv) {
  Args a;
  if (argc >= 2 && argv[1][0] != '-') a.command = argv[1];
  int i = (argc >= 2 && argv[1][0] != '-') ? 2 : 1;
  auto need = [&](const char* flag) -> std::string {
    if (i+1 >= argc) throw std::runtime_error(std::string("missing value after ")+flag);
    return argv[++i];
  };
  for (; i<argc; ++i) {
    const std::string s = argv[i];
    if (s=="--piece") a.piece=need("--piece");
    else if (s=="--shell") a.shell=need("--shell");
    else if (s=="--count") a.count=std::stoi(need("--count"));
    else if (s=="--seconds") a.seconds=std::stod(need("--seconds"));
    else if (s=="--threads") a.threads=std::stoi(need("--threads"));
    else if (s=="--seed") a.seed=std::stoull(need("--seed"));
    else if (s=="--start-scale") a.start_scale=std::stod(need("--start-scale"));
    else if (s=="--tolerance") a.tolerance=std::stod(need("--tolerance"));
    else if (s=="--clearance") a.clearance=std::stod(need("--clearance"));
    else if (s=="--output") a.output=need("--output");
    else if (s=="--progress-json") a.progress_json=true;
    else if (s=="-h" || s=="--help") { usage(); std::exit(0); }
    else throw std::runtime_error("unknown argument: "+s);
  }
  return a;
}

Polyhedron load_shape(const std::string& spec) {
  if (std::filesystem::exists(spec)) return load_obj_convex_hull(spec);
  return builtin_polyhedron(spec);
}

} // namespace

int main(int argc, char** argv) {
  try {
    const Args args = parse(argc,argv);
    if (args.command == "shapes") {
      for (const auto& n : builtin_names()) std::cout << n << '\n';
      return 0;
    }
    if (args.command != "search") { usage(); return 2; }

    const Polyhedron piece = load_shape(args.piece);
    const Polyhedron shell = load_shape(args.shell);
    SearchConfig cfg;
    cfg.count=args.count; cfg.seconds=args.seconds; cfg.threads=args.threads; cfg.seed=args.seed;
    cfg.start_scale=args.start_scale; cfg.tolerance=args.tolerance; cfg.clearance=args.clearance;

    if (!args.progress_json) {
      std::cerr << "Searching " << args.count << " x " << piece.name << " in " << shell.name
                << " for " << args.seconds << " s on " << args.threads << " worker(s)...\n";
    }
    auto progress = [&](const Packing& p) {
      if (args.progress_json) std::cout << progress_json(p,"progress") << std::endl;
      else if (p.feasible) std::cerr << "  feasible scale " << p.scale << "  max violation " << p.metrics.max_violation << '\n';
    };
    Packing result = search(piece,shell,cfg,progress);
    write_result_json(args.output,piece,shell,cfg,result,"Generated by Polyjam stochastic SAT search.");
    if (args.progress_json) std::cout << progress_json(result,"done") << std::endl;
    else {
      std::cout << (result.feasible ? "feasible" : "best infeasible") << " scale=" << result.scale
                << " maxViolation=" << result.metrics.max_violation << " -> " << args.output << '\n';
    }
    return result.feasible ? 0 : 3;
  } catch (const std::exception& e) {
    std::cerr << "polyjam: " << e.what() << '\n';
    return 1;
  }
}
